
image:
  registry: docker.io
  repository: bitnami/mediawiki
  tag: 1.31.1
  pullPolicy: Always
mediawikiUser: user
mediawikiEmail: user@example.com
mediawikiName: My Wiki
allowEmptyPassword: "yes"
externalDatabase:
  host:
  port: 3306
  user: bn_mediawiki
  password:
  database: bitnami_mediawiki
mariadb:
  enabled: true
  replication:
    enabled: false
  db:
    name: bitnami_mediawiki
    user: bn_mediawiki
  master:
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 8Gi
service:
  type: LoadBalancer
  port: 80
  httpsPort: 443
  nodePorts:
    http: ""
    https: ""
  externalTrafficPolicy: Cluster
ingress:
  enabled: false
  hosts:
  - name: wiki.local
    tls: false
    certManager: false
    tlsSecret: wiki.local-tls
    annotations:
  secrets:
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi
resources:
  requests:
    memory: 512Mi
    cpu: 300m
livenessProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
podAnnotations: {}
metrics:
  enabled: false
  image:
    registry: docker.io
    repository: lusotycoon/apache-exporter
    tag: v0.5.0
    pullPolicy: IfNotPresent
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9117"